--local symbol_map = {
--  Text = "T",
--  Method = "",
--  Function = "",
--  Constructor = "",
--  Field = "ﰠ",
--  Variable = "",
--  Class = "ﴯ",
--  Interface = "",
--  Module = "",
--  Property = "ﰠ",
--  Unit = "塞",
--  Value = "",
--  Enum = "",
--  Keyword = "",
--  Snippet = "",
--  Color = "",
--  File = "",
--  Reference = "",
--  Folder = "",
--  EnumMember = "",
--  Constant = "",
--  Struct = "פּ",
--  Event = "",
--  Operator = "",
--  TypeParameter = "P",
--}

require("lspkind").init({
  mode = "symbol_text",
  --symbol_map = symbol_map,
})
